package when2meet;

import java.io.*;
import java.util.logging.ConsoleHandler;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @author Matt Rueben
 * ^ But initial code was generated by Google Gemini.
 */
public class AvailabilityImporter {

    private static final Logger LOGGER = Logger.getLogger(AvailabilityImporter.class.getName());
    private static final ConsoleHandler CONSOLE_HANDLER = new ConsoleHandler();
    {
        CONSOLE_HANDLER.setLevel(Level.ALL);
        LOGGER.addHandler(CONSOLE_HANDLER);
        LOGGER.setLevel(Level.ALL);
    }

    public static boolean[][][] load(String csvFilename, int numPeople, int numDays, int numTimes)
    {
        String line;
        String cvsSplitBy = ","; // Delimiter used in the CSV file

        boolean[][][] availabilities = new boolean[numPeople][numDays][numTimes];

        String availableString = "Yes";

        try (InputStream is = AvailabilityImporter.class.getClassLoader().getResourceAsStream(csvFilename);
             BufferedReader br = new BufferedReader(new InputStreamReader(is)))
        {
            // Header.
            br.readLine(); // Skip it.

            // Everything after the header.
            for (int personIndex = 0; personIndex < numPeople; personIndex++)
            {
                line = br.readLine();
                String[] availability = line.split(cvsSplitBy);


                int slotIndex;
                for (int dayIndex = 0; dayIndex < numDays; dayIndex++)
                {
                    for (int timeIndex = 0; timeIndex < numTimes; timeIndex++)
                    {
                        slotIndex = (dayIndex * numTimes) + timeIndex;
                        LOGGER.fine("Person " + personIndex +
                                ", Day " + dayIndex +
                                ", Time " + timeIndex +
                                ": " + availability[slotIndex].equals(availableString));
                        availabilities[personIndex][dayIndex][timeIndex] = availability[slotIndex].equals(availableString);
                    }
                }
            }
        }
        catch (IOException e)
        {
            e.printStackTrace();
        }

        return availabilities;
    }
}