package when2meet;

import java.io.*;
import java.util.Arrays;
import java.util.logging.ConsoleHandler;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @author Matt Rueben
 * ^ But initial code was generated by Google Gemini.
 */
public class AvailabilityImporter {

    private static final Logger LOGGER = Logger.getLogger(AvailabilityImporter.class.getName());
    private static final ConsoleHandler CONSOLE_HANDLER = new ConsoleHandler();
    {
        CONSOLE_HANDLER.setLevel(Level.ALL);
        LOGGER.addHandler(CONSOLE_HANDLER);
        LOGGER.setLevel(Level.ALL);
    }

    public static String[] loadNames(String csvFilename, int numPeople)
    {
        String line;
        String cvsSplitBy = ","; // Delimiter used in the CSV file

        String[] names = new String[numPeople];

        try (InputStream is = AvailabilityImporter.class.getClassLoader().getResourceAsStream(csvFilename);
             BufferedReader br = new BufferedReader(new InputStreamReader(is)))
        {
            // Header.
            br.readLine(); // Skip it.

            // Everything after the header.
            for (int personIndex = 0; personIndex < numPeople; personIndex++)
            {
                line = br.readLine();
                String[] fields = line.split(cvsSplitBy);
                names[personIndex] = fields[0];
            }
        }
        catch (IOException e)
        {
            e.printStackTrace();
        }

        return names;
    }


    public static String[][] loadTimeTexts(String csvFilename, int numDays, int numTimes)
    {
        String line;
        String cvsSplitBy = ","; // Delimiter used in the CSV file

        String[][] timeTexts = new String[numDays][numTimes];

        try (InputStream is = AvailabilityImporter.class.getClassLoader().getResourceAsStream(csvFilename);
             BufferedReader br = new BufferedReader(new InputStreamReader(is)))
        {
            // Header.
            line = br.readLine();
            String[] fields = line.split(cvsSplitBy);
            String[] timeTexts1D = Arrays.copyOfRange(fields, 1, fields.length);

            // Repack into 2D array.
            int slotIndex;
            for (int dayIndex = 0; dayIndex < numDays; dayIndex++)
            {
                for (int timeIndex = 0; timeIndex < numTimes; timeIndex++)
                {
                    slotIndex = (dayIndex * numTimes) + timeIndex;
                    timeTexts[dayIndex][timeIndex] = timeTexts1D[slotIndex];
                }
            }
        }
        catch (IOException e)
        {
            e.printStackTrace();
        }

        return timeTexts;
    }

    public static boolean[][][] loadAvailability(String csvFilename, int numPeople, int numDays, int numTimes)
    {
        String line;
        String cvsSplitBy = ","; // Delimiter used in the CSV file

        boolean[][][] availabilities = new boolean[numPeople][numDays][numTimes];

        String availableString = "Yes";

        try (InputStream is = AvailabilityImporter.class.getClassLoader().getResourceAsStream(csvFilename);
             BufferedReader br = new BufferedReader(new InputStreamReader(is)))
        {
            // Header.
            br.readLine(); // Skip it.

            // Everything after the header.
            for (int personIndex = 0; personIndex < numPeople; personIndex++)
            {
                line = br.readLine();

                String[] fields = line.split(cvsSplitBy);
                String[] availability = Arrays.copyOfRange(fields, 1, fields.length);

                int slotIndex;
                for (int dayIndex = 0; dayIndex < numDays; dayIndex++)
                {
                    for (int timeIndex = 0; timeIndex < numTimes; timeIndex++)
                    {
                        slotIndex = (dayIndex * numTimes) + timeIndex;
                        LOGGER.fine("Person " + personIndex +
                                ", Day " + dayIndex +
                                ", Time " + timeIndex +
                                ": " + availability[slotIndex].equals(availableString));
                        availabilities[personIndex][dayIndex][timeIndex] = availability[slotIndex].equals(availableString);
                    }
                }
            }
        }
        catch (IOException e)
        {
            e.printStackTrace();
        }

        return availabilities;
    }
}