package when2meet;

import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.Graphics;
import java.awt.Color;

/**
 * @author Matt Rueben
 * ^ But initial code was generated by Google Gemini.
 */
public class When2MeetRecreator {
    private static final int BOX_WIDTH = 50;
    private static final int BOX_HEIGHT = 10;

    public static void draw(boolean[][][] availabilities)
    {
        int numPeople = availabilities.length;
        int numDays = availabilities[0].length;
        int numTimes = availabilities[0][0].length;

        JFrame frame = new JFrame("When2Meet re-creation");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(BOX_WIDTH * numDays, BOX_HEIGHT * numTimes);

        DrawingPanel panel = new DrawingPanel();
        panel.setAvailabilities(availabilities);
        panel.setBoxWidth(BOX_WIDTH);
        panel.setBoxHeight(BOX_HEIGHT);
        frame.add(panel);

        frame.setVisible(true);
    }
}

class DrawingPanel extends JPanel {

    boolean[][][] availabilities;
    int boxWidth = 50;
    int boxHeight = 100;

    protected void setAvailabilities(boolean[][][] a)
    {
        this.availabilities = a;
    }

    protected void setBoxWidth(int w)
    {
        this.boxWidth = w;
    }

    protected void setBoxHeight(int h)
    {
        this.boxHeight = h;
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); // Always call super.paintComponent()

        int numPeople = this.availabilities.length;
        int numDays = this.availabilities[0].length;
        int numTimes = this.availabilities[0][0].length;

        for (int dayIndex = 0; dayIndex < numDays; dayIndex++)
        {
            for (int timeIndex = 0; timeIndex < numTimes; timeIndex++)
            {
                int numPeopleAvailable = 0;
                for (int personIndex = 0; personIndex < numPeople; personIndex++)
                {
                    if (this.availabilities[personIndex][dayIndex][timeIndex])
                    {
                        numPeopleAvailable++;
                    }
                }
                double fractionPeopleAvailable = (double) numPeopleAvailable / numPeople;
                g.setColor(new Color(0, 100, 0, (int) (fractionPeopleAvailable * 255)));
                g.fillRect(dayIndex * boxWidth, timeIndex * boxHeight, boxWidth, boxHeight);

            }
        }
    }
}

